./vendor/bin/phpunit tests/SuccessfulUnitTest.php
./vendor/bin/phpunit tests/FollowersTest.php
./vendor/bin/phpunit tests/FollowingsTest.php
./vendor/bin/phpunit tests/FavoritesTest.php
./vendor/bin/phpunit tests/ErrorUnitTest.php
./vendor/bin/phpunit tests/PostTooLongTweetTest.php
./vendor/bin/phpunit tests/PostGetAndDeleteTweetTest.php
./vendor/bin/phpunit tests/NotValidAPIKeyTest.php
./vendor/bin/phpunit tests/WrongTypeofParameterTest.php
./vendor/bin/phpunit tests/WrongTypeofParameterCountTest.php
./vendor/bin/phpunit tests/NotExistingTweetTest.php
